name: Lint Reusable Workflow

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
      os:
        required: true
        type: string
jobs:
  lint:
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
      - name: Cache python packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: python-${{inputs.os}}-${{inputs.python-version}}
      - name: Upgrade pip
        id: upgrade_pip
        run: |
          python -m pip install --upgrade pip
        shell: bash
      - name: Install linting dependencies
        id: install-lint-reqs
        run: |
          make install-lint
          make install-pre-commit
        shell: bash
      - name: Run lint
        if: ${{ !cancelled() && steps.install-lint-reqs.outcome == 'success' }}
        run: |
          make lint
        shell: bash
      - name: Run type checking
        if: ${{ !cancelled() && steps.install-lint-reqs.outcome == 'success' }}
        run: |
          make type-check
        shell: bash
