name: Unit Tests Reusable Workflow

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
      os:
        required: true
        type: string
jobs:
  unit-tests:
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip
        shell: bash
      - name: Install dependencies
        run: |
          make install-test
        shell: bash
      - name: Run unit tests
        run: make unit-test
        shell: bash
